# Download and Join Spreadsheets

Data repositories:
| Service | Data Source (Kaggle) |
| :--- | :--- |
| Netflix | [Netflix Shows](https://www.kaggle.com/datasets/shivamb/netflix-shows) |
| Prime Video | [Amazon Prime Movies and TV Shows](https://www.kaggle.com/datasets/shivamb/amazon-prime-movies-and-tv-shows) |
| Disney+ | [Disney Movies and TV Shows](https://www.kaggle.com/datasets/shivamb/disney-movies-and-tv-shows) |
| Hulu | [Hulu Movies and TV Shows](https://www.kaggle.com/datasets/shivamb/hulu-movies-and-tv-shows) |

### All Imports

In [1]:
import pandas as pd

### Downloads

#### Netflix

In [2]:
!curl -L -o spreadsheets/netflix_shows.zip "https://www.kaggle.com/api/v1/datasets/download/shivamb/netflix-shows"
!unzip spreadsheets/netflix_shows.zip -d spreadsheets/
!rm -r spreadsheets/netflix_shows.zip
!mv spreadsheets/netflix_titles.csv spreadsheets/netflix.csv
netflix = pd.read_csv("spreadsheets/netflix.csv")
netflix.head()

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1368k  100 1368k    0     0   647k      0  0:00:02  0:00:02 --:--:-- 1832k
Archive:  spreadsheets/netflix_shows.zip
  inflating: spreadsheets/netflix_titles.csv

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

#### Prime

In [3]:
!curl -L -o spreadsheets/prime_shows.zip "https://www.kaggle.com/api/v1/datasets/download/shivamb/amazon-prime-movies-and-tv-shows"
!unzip spreadsheets/prime_shows.zip -d spreadsheets/
!rm -r spreadsheets/prime_shows.zip
!mv spreadsheets/amazon_prime_titles.csv spreadsheets/prime.csv
prime = pd.read_csv("spreadsheets/prime.csv")
prime.head()

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1650k  100 1650k    0     0   776k      0  0:00:02  0:00:02 --:--:-- 1171k
Archive:  spreadsheets/prime_shows.zip
  inflating: spreadsheets/amazon_prime_titles.csv

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

#### Disney+

In [4]:
!curl -L -o spreadsheets/disney_plus_shows.zip "https://www.kaggle.com/api/v1/datasets/download/shivamb/disney-movies-and-tv-shows"
!unzip spreadsheets/disney_plus_shows.zip -d spreadsheets/
!rm -r spreadsheets/disney_plus_shows.zip
!mv spreadsheets/disney_plus_titles.csv spreadsheets/disney.csv
disney = pd.read_csv("spreadsheets/disney.csv")
disney.head()

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  130k  100  130k    0     0  76428      0  0:00:01  0:00:01 --:--:--  191k
Archive:  spreadsheets/disney_plus_shows.zip
  inflating: spreadsheets/disney_plus_titles.csv

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...

#### Hulu

In [5]:
!curl -L -o spreadsheets/hulu_shows.zip "https://www.kaggle.com/api/v1/datasets/download/shivamb/hulu-movies-and-tv-shows"
!unzip spreadsheets/hulu_shows.zip -d spreadsheets/
!rm -r spreadsheets/hulu_shows.zip
!mv spreadsheets/hulu_titles.csv spreadsheets/hulu.csv
hulu = pd.read_csv("spreadsheets/hulu.csv")
hulu.head()

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  421k  100  421k    0     0   217k      0  0:00:01  0:00:01 --:--:--  361k
Archive:  spreadsheets/hulu_shows.zip
  inflating: spreadsheets/hulu_titles.csv

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r..."
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...
3,s4,Movie,Gaia,NaN,NaN,NaN,"October 22, 2021",2021,R,97 min,Horror,A forest ranger and two survivalists with a cu...
4,s5,Movie,Settlers,NaN,NaN,NaN,"October 22, 2021",2021,NaN,104 min,"Science Fiction, Thriller",Mankind's earliest settlers on the Martian fro...

### Join

In [6]:
netflix["streaming"] = "Netflix"
prime["streaming"] = "Prime Video"
disney["streaming"] = "Disney+"
hulu["streaming"] = "Hulu"

streamings = [netflix, prime, disney, hulu]
data = pd.concat(streamings, ignore_index=True)
data.groupby("streaming").count()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
streaming,,,,,,,,,,,,
Disney+,1450,1450,1450,977,1260,1231,1447,1450,1447,1450,1450,1450
Hulu,3073,3073,3073,3,0,1620,3045,3073,2553,2594,3073,3069
Netflix,8807,8807,8807,6173,7982,7976,8797,8807,8803,8804,8807,8807
Prime Video,9668,9668,9668,7585,8435,672,155,9668,9331,9668,9668,9668

### Save

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22998 entries, 0 to 22997
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       22998 non-null  object
 1   type          22998 non-null  object
 2   title         22998 non-null  object
 3   director      14738 non-null  object
 4   cast          17677 non-null  object
 5   country       11499 non-null  object
 6   date_added    13444 non-null  object
 7   release_year  22998 non-null  int64
 8   rating        22134 non-null  object
 9   duration      22516 non-null  object
 10  listed_in     22998 non-null  object
 11  description   22994 non-null  object
 12  streaming     22998 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.3+ MB

In [8]:
data = data.drop("show_id", axis=1)
data = data.drop("director", axis=1)
data = data.drop("cast", axis=1)
data["type"] = data["type"].astype('category')
data['title'] = data['title'].astype('string')

data["country"] = data["country"].astype('category')
data['date_added'] = pd.to_datetime(
    data['date_added'], 
    format='%B %d, %Y',
    errors='coerce'
)
data['release_year'] = data['release_year'].astype('int16')
data["rating"] = data["rating"].astype('category')

data["listed_in"] = data["listed_in"].astype('category')
data['description'] = data['description'].astype('string')
data["streaming"] = data["streaming"].astype('category')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22998 entries, 0 to 22997
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          22998 non-null  category
 1   title         22998 non-null  string
 2   country       11499 non-null  category
 3   date_added    13356 non-null  datetime64[ns]
 4   release_year  22998 non-null  int16
 5   rating        22134 non-null  category
 6   duration      22516 non-null  object
 7   listed_in     22998 non-null  category
 8   description   22994 non-null  string
 9   streaming     22998 non-null  category
dtypes: category(5), datetime64[ns](1), int16(1), object(1), string(2)
memory usage: 1.0+ MB

In [10]:
data.to_csv("spreadsheets/streaming.csv", index=False)